POST https://intense-thicket-05424.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Isaac Asimov",
    "number": "11-22-334455"
}

### Missing name
POST https://intense-thicket-05424.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": "11-22-334455"
}

### Missing number
POST https://intense-thicket-05424.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Isaac Asimov"
}

### No content
POST https://intense-thicket-05424.herokuapp.com/api/persons
Content-Type: application/json

{

}


### Localhost
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Isaac Asimov",
    "number": "11-22-334455"
}